[package]
name = "iroha_schema"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_schema_derive = { workspace = true }

serde = { workspace = true, features = ["derive", "alloc"] }
fixnum = { workspace = true, features = ["i64"] }

[dev-dependencies]
parity-scale-codec = { version = "3.2.1", default-features = false, features = ["derive", "full"] }
impls = "1.0.3"
