[package]
name = "iroha_primitives_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
syn = "1.0.107"
proc-macro2 = "1.0.49"

[dev-dependencies]
# needed for doc-tests to pass
iroha_primitives = { path = ".." }