[package]
name = "iroha_version_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-error = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
iroha_version = { workspace = true, features = ["scale", "json"] }
iroha_macro = { workspace = true }

parity-scale-codec = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }

trybuild = { workspace = true }
